#!/usr/bin/env bash
# This script prints "To infinity and beyond" every 2 seconds and prints "OK" on SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "I am invincible!!!"
  sleep 2
done
