#!/usr/bin/env bash
# Prints numbers 1-10 replacing 4 with "bad luck" and 8 with "your chance"

count=1
while [ $count -le 10 ]; do
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "your chance"
  else
    echo "$count"
  fi
  count=$((count + 1))
done
