#!/usr/bin/env bash
# Print numbers 1 to 20 with substitutions using while and case

num=1
while [ $num -le 20 ]; do
  case $num in
    36) echo "4 9" ;;       # 36 is LCM of 4 and 9 within 1-20 (actually it's above 20, so no, remove)
    # Actually, 36 > 20, so we need a better approach.
    # Since case matches exact values, we need to match multiples with pattern.
    # Bash case supports patterns but not arithmetic, so we need a trick:
    # We'll match multiples of 4, 9, and both in case.
  esac

  # Since case can't do arithmetic, let's do this:
  case $((num % 36)) in
    0) echo "4 9" ;;
    *) 
      case $((num % 4)) in
        0) echo "4" ;;
        *) 
          case $((num % 9)) in
            0) echo "9" ;;
            *) echo "$num" ;;
          esac
      esac
    ;;
  esac
  num=$((num + 1))
done
