#!/usr/bin/env bash
# Print numbers 1 to 20 and superstition messages after matching numbers

num=1
while [ $num -le 20 ]; do
  echo "$num"
  case $num in
    4) echo "bad luck from China" ;;
    8) echo "bad luck from Japan" ;;
    17) echo "bad luck from Italy" ;;
  esac
  num=$((num + 1))
done
