#!/usr/bin/env bash
# Print numbers 1 to 20 with superstition messages

i=1
while [ $i -le 20 ]; do
  echo "$i"
  case $i in
    4) echo "bad luck from China" ;;
    8) echo "bad luck from Japan" ;;
    17) echo "bad luck from Italy" ;;
  esac
  i=$((i + 1))
done
