#!/usr/bin/env bash
# Check the file "school" and print its status

if [[ -e school ]]; then
  if [[ -d school ]]; then
    echo "school exists but it’s a directory"
  elif [[ -f school ]]; then
    if [[ ! -s school ]]; then
      echo "school exists but empty"
    else
      echo "school exists and is a regular file"
    fi
  fi
else
  echo "school doesn’t exist"
fi
